name: Build and Push Docker Image

on:
  push:
    branches:
      - master

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_TAG: 1.1
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          karsixp:latest
          karsixp:${{ github.sha }}
          karsixp:${{ env.DOCKER_TAG }}

    - name: Create Git tag
      if: success()
      run: git tag -a ${{ env.DOCKER_TAG }} -m "Tagging release version ${{ env.DOCKER_TAG }}"
      env:
        DOCKER_TAG: ${{ github.ref }}
